# Generated by Django 4.0.4 on 2022-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
