# Generated by Django 4.0.4 on 2022-06-03 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_slug_alter_ad_name_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
